// Auto-generated by make — do not edit
let buildVersion = "1.2.0"
let buildCommit = "f5a34d5"
let buildBranch = "main"
let buildDate = "2026-04-24 11:22:40 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
