// Auto-generated by make — do not edit
let buildVersion = "0.8.3"
let buildCommit = "8425de5"
let buildBranch = "main"
let buildDate = "2026-04-05 09:04:05 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
