// Auto-generated by make — do not edit
let buildVersion = "1.3.6"
let buildCommit = "b6d4524"
let buildBranch = "main"
let buildDate = "2026-05-20 15:26:44 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
